version: '3.3'
services:
  test-server:
    build: .
    image: plusfries:latest
    ports:
      - 9090:9090
    volumes:
      - $HOME/.npm:/.npm
    environment:
      - DB_STORAGE=":memory:"
      - PORT=9090
